language: bash

before_install:
  - sudo apt update && sudo apt install -y shellcheck

script:

  - ls -l
  - bash test.sh
   - ls -l
  - pwd
  - cat file




notifications:
          email:
                  on_success: never